---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: abc-
spec:
  template:
    spec:
      containers:
      - name: abcd
        image: perl
        command: ["echo"]
        args: ["wow2: $TFCLOUD_USERNAME"]
        env:
          - name: TFCLOUD_USERNAME
            valueFrom:
              secretKeyRef:
                name: tfcloudtoken
                key: user
      restartPolicy: OnFailure
  backoffLimit: 4
