---
apiVersion: batch/v1
kind: Job
metadata:
  name: sec7
spec:
  template:
    spec:
      containers:
      - name: sec7
        image:
          repository: perl
          tag: v1.0.0
        command: ["echo"]
        args: ["wow2: $TFCLOUD_USERNAME"]
        env:
          - name: TFCLOUD_USERNAME
            valueFrom:
              secretKeyRef:
                name: tfcloudtoken
                key: user
      restartPolicy: OnFailure
  backoffLimit: 4
