---
apiVersion: batch/v1
kind: Job
metadata:
  name: sec6
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 100
      containers:
      - name: sec6
        image: perl
        command: ["echo"]
        args: ["wow2: $TFCLOUD_USERNAME"]
        env:
          - name: TFCLOUD_USERNAME
            valueFrom:
              secretKeyRef:
                name: tfcloudtoken
                key: user
      restartPolicy: Always
  backoffLimit: 4
