---
apiVersion: batch/v1
kind: Job
metadata:
  name: abc
spec:
  template:
    spec:
      containers:
      - name: abc
        image: perl
        command: ["echo"]
        args: ["wow2: $TFCLOUD_USERNAME"]
        env:
          - name: TFCLOUD_USERNAME
            valueFrom:
              secretKeyRef:
                name: tfcloudtoken
                key: user
      restartPolicy: OnFailure
  backoffLimit: 4
