apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfcloudtoken
  namespace: default
spec:
  encryptedData:
    password: AgAS88FYaIofdYGwqGWcxaK9fDCBexbK46BZ1TWwXmnKPcHSNoTjdx24JrMDIMFPzyKfgKTBPtJaqBS34sg8LHYEmqgi+GSoDN5ccuIS897NpV07A2TukhGVYg4NDGzrTZU48+Qaqxp5CSbFMErbs7gVhe6jo+GgzoxcAEA9ZCa5AvbRXvXP6y1YQ6ikWacjEo8YcQ65h2QWTPi5WK2LoE/SGhWTxb4EZCZIpPnjlDQQgjEE6zsvO9QQKPAnIO1PQEZlzgUjtYRDXY3vNfKwXpn8ItTtE47uEIFUSgpne1MTGWiPBt+SWZ5kwsLVBa3h2eUK8o+Ph5y1ngREy2zshcl0CIisuQC5znJUEuHqgBiTM4clQlfIJYByPs6T8CG0tf24a9iik/Xlglna1O7R9Vs0NTE3MNm9M1aYtx6kEkRa1n734GUEhUM8B2cinqngQvqztuc+/nWf+YnGjYRaTP4tz4a6b+GuDvYlgXKwBgmO2niCqv+CggjdWsbHqPMDfeSubDhrVNis74FhHwjkNUHQSYUIW82Uwd6PKOQN3Y8pp7NIs81vOW6ueqrVMadBDcpMymXHdEtVe1lp4cLRlWTKQHCrFHrRu6ZdW4Hl/8KEbEbb2JR8rwdyvMYWQoo+xNdrXzd6uHy0HdNKe09yX7Dw2qODYvmjXEgHsUFjvMkZdPbmocTOh1f9bZCM7OD7OHDnFFvNcA==
    user: AgCptvk2YPA43fd29T2DIrYfZTzwxBT+Hb3VN3EAHSB9zb72GxCG0FSaLRZ9SM3DnUVvtA8Odk4aMfVF61ds5orGNYH7Tk6F8KyTfApYvbC6MSfkynej0t8mmuOV6bP0dLRqn7DmL0pPTtj7N/Z1Bpyp0oUwfP5548B+hnhZt1mcgijZrH/mjBB/H5eEvq0ELSJ4Ain6iSiPvQq1boTY678Q8bhG44W08UVKPXn2Q6oIuOKFmtIq29FmPVCvzBGHk4LNcrM5YbolNSIM1tPEe887w2m0Gqs4a2eqmT6Kg6QSY2+cqGuvRHeLzWl4pnD1UJEXtSdmGOfTsfHdwL3D1GNHxGk7PVQCLptUSvLUFXrCsov4hdzt/pP9fDjb3zaQIc7T9NIMY/JJkpW6OZYZM/bic3JrPl6JrXGyb1OrscTTGCLPAUBw5JaBUarP2rG8d1PNOUW76T8GOnAAt7GoTu7jKYWfx1mIbLAwHvbsYixquJUBmN3HFnxAZ/QQvdvtg+8BxEAUlROFHxY7wspTbGWbxnQmn81vRO8VngE2ZYe5FRpG+iZB9XT1KNbg9uy9LDMfhkjzw2u/yMa1utxoLNXSuTgkBWHAh20roQfeFtaunN2u9YoofusBDFo+N1Y5tGo6Bm+FbTGboZe9jHxkmC5V0N4TBqFUHpXHHcUU6su5KwR4WjguN0reQ34aV7ugMyJZI8CPRw==
  template:
    metadata:
      creationTimestamp: null
      name: tfcloudtoken
      namespace: default

